export class PermissionsEnum {

    // USERS
    static USERS_GET_ALL = "USERS_GET_ALL";
    static USERS_ADD = "USERS_ADD";
    static USERS_ARCHIVE = "USERS_ARCHIVE";
    static USERS_ACTIVATE = "USERS_ACTIVATE";
    static USERS_UPDATE = "USERS_UPDATE";
    static USERS_GET_ALL_AVAILABLE_USER_ROLES = "USERS_GET_ALL_AVAILABLE_USER_ROLES";

    // COMPANIES
    static COMPANIES_GET_ALL = "COMPANIES_GET_ALL";
    static COMPANIES_GET = "COMPANIES_GET";
    static COMPANIES_IGNORE = "COMPANIES_IGNORE";

    // DEALWATCH
    static DEALWATCH_PROCESS = "DEALWATCH_PROCESS";

    // PEOPLE_WATCH
    static PEOPLE_WATCH_RUN_REPORTS = "PEOPLE_WATCH_RUN_REPORTS";

    // CAPSULE_GET_NOTES
    static CAPSULE_GET_NOTES = "CAPSULE_GET_NOTES";

}
